-- NÚCLEO ERP · Migración 0016 · NÚCLEO COMEX (Fase 9)
-- Carpetas de importación operativas: tasas ingresadas por el usuario, costo estimado vs. real,
-- costos anulables y contenido de Incoterms. Sin aranceles ni tasas en la base (COMEX_RULES.md).

ALTER TABLE imports ADD COLUMN vat_ppm INTEGER CHECK (vat_ppm IS NULL OR vat_ppm BETWEEN 0 AND 1000000);
ALTER TABLE imports ADD COLUMN vat_recoverable INTEGER NOT NULL DEFAULT 1 CHECK (vat_recoverable IN (0, 1));
-- Foto del costo estimado al confirmar la importación (para comparar "estimaste $X, costó $Y").
ALTER TABLE imports ADD COLUMN estimated_landed_clp INTEGER;
ALTER TABLE imports ADD COLUMN estimated_at TEXT;
ALTER TABLE imports ADD COLUMN void_reason TEXT;
ALTER TABLE import_items ADD COLUMN estimated_unit_cost_e4 INTEGER;
-- Los costos reales con cuenta por pagar no se borran: se anulan.
ALTER TABLE import_costs ADD COLUMN status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'anulado'));
ALTER TABLE import_costs ADD COLUMN document_ref TEXT;
ALTER TABLE import_costs ADD COLUMN cost_date TEXT CHECK (cost_date IS NULL OR date(cost_date) IS cost_date);

CREATE INDEX idx_imports_list ON imports (is_scenario, stage, created_at);
CREATE INDEX idx_import_costs_supplier ON import_costs (supplier_id) WHERE supplier_id IS NOT NULL;

-- El rol Compras gestiona importaciones.
INSERT OR IGNORE INTO role_permissions (role_id, permission_code)
SELECT id, 'comex.editar' FROM roles WHERE code = 'compras';

-- Incoterms® 2020: resumen propio (quién entrega, dónde pasa el riesgo, qué costos agrega el importador
-- en NÚCLEO). Contenido versionado y reemplazable; no es el texto oficial de la ICC.
INSERT INTO incoterm_definitions (code, version, name, content_json, source) VALUES
('EXW', '2020', 'En fábrica', json('{"grupo":"E","transporte":"cualquiera","entrega":"El vendedor deja la mercadería a disposición en su local, sin cargarla ni despacharla para exportación.","riesgo":"Pasa al comprador desde que la mercadería está a su disposición en el local del vendedor.","vendedor":["Embalaje"],"comprador":["Carga en origen","Despacho de exportación","Flete internacional","Seguro","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":["otros","flete","seguro"],"nota":"Agrega como costo los gastos en origen (carga y despacho de exportación), además del flete y el seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('FCA', '2020', 'Franco transportista', json('{"grupo":"F","transporte":"cualquiera","entrega":"El vendedor entrega la mercadería, despachada para exportación, al transportista que designa el comprador en el lugar convenido.","riesgo":"Pasa al comprador al entregarla al transportista.","vendedor":["Despacho de exportación","Entrega al transportista"],"comprador":["Flete internacional","Seguro","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":["flete","seguro"],"nota":"Agrega el flete internacional y el seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('FAS', '2020', 'Franco al costado del buque', json('{"grupo":"F","transporte":"maritimo","entrega":"El vendedor deja la mercadería al costado del buque en el puerto de embarque, despachada para exportación.","riesgo":"Pasa al comprador cuando la mercadería está al costado del buque.","vendedor":["Despacho de exportación","Traslado al puerto de embarque"],"comprador":["Carga al buque","Flete marítimo","Seguro","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":["flete","seguro"],"nota":"Agrega el flete (incluida la carga al buque) y el seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('FOB', '2020', 'Franco a bordo', json('{"grupo":"F","transporte":"maritimo","entrega":"El vendedor entrega la mercadería a bordo del buque en el puerto de embarque, despachada para exportación.","riesgo":"Pasa al comprador cuando la mercadería está a bordo.","vendedor":["Despacho de exportación","Carga a bordo"],"comprador":["Flete marítimo","Seguro","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":["flete","seguro"],"nota":"Agrega el flete marítimo y el seguro: el precio no los incluye."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('CFR', '2020', 'Costo y flete', json('{"grupo":"C","transporte":"maritimo","entrega":"El vendedor entrega a bordo en el puerto de embarque y paga el flete hasta el puerto de destino.","riesgo":"Pasa al comprador cuando la mercadería está a bordo en origen (aunque el vendedor pague el flete).","vendedor":["Despacho de exportación","Carga a bordo","Flete marítimo"],"comprador":["Seguro","Descarga si no está en el flete","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":["seguro"],"nota":"El precio incluye el flete; agrega el seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('CIF', '2020', 'Costo, seguro y flete', json('{"grupo":"C","transporte":"maritimo","entrega":"El vendedor entrega a bordo en el puerto de embarque y paga el flete y un seguro de cobertura mínima hasta el puerto de destino.","riesgo":"Pasa al comprador cuando la mercadería está a bordo en origen.","vendedor":["Despacho de exportación","Carga a bordo","Flete marítimo","Seguro de cobertura mínima"],"comprador":["Descarga si no está en el flete","Despacho de importación, derechos e impuestos","Transporte hasta su bodega"],"agregar":[],"nota":"El precio ya incluye flete y seguro: no los agregues como costo."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('CPT', '2020', 'Transporte pagado hasta', json('{"grupo":"C","transporte":"cualquiera","entrega":"El vendedor entrega al primer transportista y paga el transporte hasta el lugar de destino convenido.","riesgo":"Pasa al comprador al entregar la mercadería al primer transportista.","vendedor":["Despacho de exportación","Transporte hasta el destino convenido"],"comprador":["Seguro","Despacho de importación, derechos e impuestos","Transporte desde el destino convenido a su bodega"],"agregar":["seguro"],"nota":"El precio incluye el transporte; agrega el seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('CIP', '2020', 'Transporte y seguro pagados hasta', json('{"grupo":"C","transporte":"cualquiera","entrega":"El vendedor entrega al primer transportista y paga el transporte y un seguro de cobertura amplia hasta el destino convenido.","riesgo":"Pasa al comprador al entregar la mercadería al primer transportista.","vendedor":["Despacho de exportación","Transporte hasta el destino convenido","Seguro de cobertura amplia"],"comprador":["Despacho de importación, derechos e impuestos","Transporte desde el destino convenido a su bodega"],"agregar":[],"nota":"El precio ya incluye transporte y seguro."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('DAP', '2020', 'Entregada en lugar', json('{"grupo":"D","transporte":"cualquiera","entrega":"El vendedor pone la mercadería en el lugar de destino convenido, lista para descargar.","riesgo":"El vendedor asume el riesgo hasta el lugar de destino.","vendedor":["Despacho de exportación","Transporte y seguro hasta el destino"],"comprador":["Descarga","Despacho de importación, derechos e impuestos"],"agregar":[],"nota":"El precio incluye transporte hasta el destino. Pregunta a tu agente cómo separar los gastos posteriores a la llegada para el valor aduanero."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('DPU', '2020', 'Entregada en lugar descargada', json('{"grupo":"D","transporte":"cualquiera","entrega":"El vendedor entrega la mercadería descargada en el lugar de destino convenido.","riesgo":"El vendedor asume el riesgo hasta descargar en destino.","vendedor":["Despacho de exportación","Transporte y seguro hasta el destino","Descarga"],"comprador":["Despacho de importación, derechos e impuestos"],"agregar":[],"nota":"El precio incluye transporte y descarga en destino. Consulta a tu agente por el valor aduanero."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.'),
('DDP', '2020', 'Entregada derechos pagados', json('{"grupo":"D","transporte":"cualquiera","entrega":"El vendedor entrega en el destino convenido con la importación despachada y los derechos e impuestos pagados.","riesgo":"El vendedor asume el riesgo hasta el destino.","vendedor":["Todo el transporte y seguro","Despacho de exportación e importación","Derechos e impuestos de importación"],"comprador":["Descarga"],"agregar":[],"nota":"El vendedor paga derechos e impuestos: no los agregues salvo que te los cobren aparte."}'), 'Resumen propio de Incoterms® 2020 (Cámara de Comercio Internacional). Referencial: revisa tu contrato y consulta a tu agente de aduana.');
